CREATE OR REPLACE PROCEDURE atualizar_cli_segmercado
(p_ID CLIENTE.ID%TYPE, p_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE)
IS
BEGIN
    UPDATE CLIENTE SET SEGMERCADO_ID = p_SEGMERCADO_ID
    WHERE ID = p_ID;
    COMMIT;
END;

SELECT * FROM cliente;

INSERT INTO CLIENTE(ID, RAZAO_SOCIAL, SEGMERCADO_ID) VALUES (2,'33324', 1);

EXECUTE atualizar_cli_segmercado (1,2);

DECLARE
    v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%TYPE := 1;
    v_I NUMBER(3) := 1;
BEGIN
    LOOP
        atualizar_cli_segmercado(v_I, v_SEGMERCADO_ID);
        v_I := v_I + 1;
    EXIT WHEN v_I > 6;
    END LOOP;
END;